# Generated by Django 3.1.7 on 2021-05-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludeKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
