# Generated by Django 3.1.5 on 2021-05-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludeKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='ans_code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='questions',
            name='tags',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='content',
            field=models.TextField(default=None, max_length=1200),
        ),
    ]
