# Generated by Django 3.1.7 on 2021-05-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_auto_20210513_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='ans_code',
            field=models.TextField(default=None),
        ),
    ]
