# Generated by Django 3.1.5 on 2021-05-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_auto_20210505_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='a_date',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='a_time',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='q_date',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='q_time',
        ),
    ]
