# Generated by Django 3.1.7 on 2021-05-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_questions_que_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='que_code',
            field=models.TextField(default=None),
        ),
    ]
