# Generated by Django 3.1.5 on 2021-05-05 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_questions_q_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='q_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
