# Generated by Django 3.1.5 on 2021-05-05 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0006_auto_20210505_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='a_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
