# Generated by Django 3.1.5 on 2021-05-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0007_answers_a_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.CharField(choices=[('sviit', 'SVIIT'), ('svim', 'SVIM'), ('svil', 'SVIL')], max_length=5),
        ),
    ]
