# Generated by Django 3.1.5 on 2021-05-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0008_auto_20210507_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.CharField(blank=True, choices=[('sviit', 'SVIIT'), ('svim', 'SVIM'), ('svil', 'SVIL')], max_length=5, null=True),
        ),
    ]
