# Generated by Django 3.1.5 on 2021-05-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0009_auto_20210507_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
