# Generated by Django 3.1.5 on 2021-04-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210406_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='idCard',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
