# Generated by Django 3.1.5 on 2021-04-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_idcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idCard',
            field=models.FileField(blank=True, null=True, upload_to='../static'),
        ),
    ]
