# Generated by Django 3.1.5 on 2021-04-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210418_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='idcardstring',
            new_name='idCardString',
        ),
    ]
